sudo: false
language: python
python: "3.5"
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=lint
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
addons:
    apt:
        packages:
            - ed
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
